
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a recipe based on a list of ingredients and dish type, including nutritional information.
 *
 * - generateRecipe - A function that generates a recipe.
 * - GenerateRecipeInput - The input type for the generateRecipe function.
 * - GenerateRecipeOutput - The return type for the generateRecipe function.
 * - NutritionalInfo - The type for nutritional information.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecipeInputSchema = z.object({
  ingredients: z
    .array(z.string())
    .describe('A list of ingredients to use in the recipe. Example: ["Chicken breast", "Broccoli", "Soy sauce"]'),
  dishType: z.string().describe('The type of dish to generate. Example: "Stir-fry" or "Quick weeknight dinner"'),
});
export type GenerateRecipeInput = z.infer<typeof GenerateRecipeInputSchema>;

const NutritionalInfoSchema = z.object({
  calories: z.string().describe('Estimated calories per serving. Example: "450 kcal"'),
  protein: z.string().describe('Estimated protein per serving. Example: "35g"'),
  carbohydrates: z.string().describe('Estimated carbohydrates per serving. Example: "40g"'),
  fat: z.string().describe('Estimated fat per serving. Example: "20g"'),
  // Consider adding servingSize: z.string().optional().describe('Serving size for which nutritional info is calculated. Example: "1 serving (approx. 300g)"')
});
export type NutritionalInfo = z.infer<typeof NutritionalInfoSchema>;

const GenerateRecipeOutputSchema = z.object({
  recipeName: z.string().describe('The name of the generated recipe. Example: "Easy Chicken and Broccoli Stir-fry"'),
  ingredients: z.array(z.string()).describe('The ingredients for the recipe, with precise quantities and units. Example: ["1 lb chicken breast, cut into 1-inch pieces", "1 cup broccoli florets", "2 tbsp soy sauce"]'),
  instructions: z.array(z.string()).describe('Step-by-step instructions for the recipe. Example: ["1. Heat oil in a large skillet or wok over medium-high heat.", "2. Add chicken and cook until browned."]'),
  prepTime: z.string().optional().describe('Estimated preparation time. Example: "15 minutes"'),
  cookTime: z.string().optional().describe('Estimated cooking time. Example: "20 minutes"'),
  servings: z.string().optional().describe('Number of servings the recipe makes. Example: "4 servings"'),
  tips: z.array(z.string()).optional().describe('Optional tips or variations for the recipe. Example: ["For a spicier dish, add 1/2 tsp red pepper flakes with the garlic.", "Serve over rice or noodles."]'),
  nutritionalInfo: NutritionalInfoSchema.describe('Estimated nutritional information per serving for the generated recipe.'),
});
export type GenerateRecipeOutput = z.infer<typeof GenerateRecipeOutputSchema>;

export async function generateRecipe(input: GenerateRecipeInput): Promise<GenerateRecipeOutput> {
  return generateRecipeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRecipePrompt',
  input: {schema: GenerateRecipeInputSchema},
  output: {schema: GenerateRecipeOutputSchema},
  prompt: `You are a creative and renowned world-class chef and nutritionist, tasked with crafting an exceptional and informative recipe.
Based on the provided list of ingredients and the desired dish type, generate a complete, easy-to-follow recipe suitable for a home cook.

Input:
Ingredients available: {{#each ingredients}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Desired Dish Type: {{{dishType}}}

Your generated recipe must include:
1.  \`recipeName\`: A creative and appealing name for the dish.
2.  \`ingredients\`: A detailed list of all necessary ingredients for the recipe.
    *   Include precise quantities using common culinary units (Measurements to be Indian Specific) (e.g., "1 cup (240ml) all-purpose flour", "2 tablespoons olive oil", "150g boneless, skinless chicken thighs", "1 teaspoon dried oregano").
    *   Incorporate the "Ingredients available" and supplement with other common ingredients to make a complete and delicious dish.
3.  \`instructions\`: Clear, step-by-step preparation and cooking instructions.
    *   Be specific about cooking times, temperatures, and techniques.
    *   Include any important prep work (e.g., "Preheat oven to 200°C (400°F).", "Dice onions and mince garlic.").
4.  \`nutritionalInfo\`: Estimated nutritional information PER SERVING for the final recipe. This is a MANDATORY field. Calculate this based on the ingredients and quantities in your generated recipe. It must include:
    *   \`calories\`: Estimated calories per serving (e.g., "450 kcal").
    *   \`protein\`: Estimated protein per serving (e.g., "35g").
    *   \`carbohydrates\`: Estimated carbohydrates per serving (e.g., "40g").
    *   \`fat\`: Estimated fat per serving (e.g., "20g").

Additionally, please try to include the following for an even better recipe (these fields are optional in the schema but highly encouraged):
*   \`prepTime\`: Estimated preparation time (e.g., "15 minutes").
*   \`cookTime\`: Estimated cooking time (e.g., "25 minutes").
*   \`servings\`: Number of servings the recipe yields (e.g., "4 servings"). This is important for the per-serving nutritional calculation.
*   \`tips\`: An array of strings with helpful tips, variations, or serving suggestions (e.g., ["For a gluten-free version, use tamari instead of soy sauce.", "Garnish with chopped cilantro before serving."]).

Structure your response strictly according to the output schema.
`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_ONLY_HIGH',
      },
    ],
  }
});

const generateRecipeFlow = ai.defineFlow(
  {
    name: 'generateRecipeFlow',
    inputSchema: GenerateRecipeInputSchema,
    outputSchema: GenerateRecipeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
     if (!output) {
      throw new Error("AI failed to provide an output for recipe generation.");
    }
    // Ensure nutritionalInfo is present, even if the model somehow misses it despite the prompt.
    if (!output.nutritionalInfo) {
        console.warn("AI output missing nutritionalInfo in recipe generation, attempting to add default. This indicates a prompt issue.");
        output.nutritionalInfo = { calories: "N/A", protein: "N/A", carbohydrates: "N/A", fat: "N/A" };
    }
    return output;
  }
);
