// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a recipe based on a list of ingredients and dish type.
 *
 * - generateRecipe - A function that generates a recipe.
 * - GenerateRecipeInput - The input type for the generateRecipe function.
 * - GenerateRecipeOutput - The return type for the generateRecipe function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecipeInputSchema = z.object({
  ingredients: z
    .array(z.string())
    .describe('A list of ingredients to use in the recipe.'),
  dishType: z.string().describe('The type of dish to generate.'),
});
export type GenerateRecipeInput = z.infer<typeof GenerateRecipeInputSchema>;

const GenerateRecipeOutputSchema = z.object({
  recipeName: z.string().describe('The name of the generated recipe.'),
  ingredients: z.array(z.string()).describe('The ingredients for the recipe, with quantities.'),
  instructions: z.array(z.string()).describe('Step-by-step instructions for the recipe.'),
});
export type GenerateRecipeOutput = z.infer<typeof GenerateRecipeOutputSchema>;

export async function generateRecipe(input: GenerateRecipeInput): Promise<GenerateRecipeOutput> {
  return generateRecipeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRecipePrompt',
  input: {schema: GenerateRecipeInputSchema},
  output: {schema: GenerateRecipeOutputSchema},
  prompt: `You are a world-class chef. Generate a recipe based on the following ingredients and dish type.

Ingredients: {{#each ingredients}}{{{this}}}, {{/each}}
Dish Type: {{{dishType}}}

Recipe should include a list of ingredients with quantities and step-by-step instructions.

Format the ingredients as a list of strings, including quantities, and the instructions as a numbered list of strings.

Recipe Name: (The name of the recipe)
Ingredients: (A list of ingredients with quantities)
Instructions: (A numbered list of instructions)
`,
});

const generateRecipeFlow = ai.defineFlow(
  {
    name: 'generateRecipeFlow',
    inputSchema: GenerateRecipeInputSchema,
    outputSchema: GenerateRecipeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
